/**
 *
 *
  _____                      _              _ _ _     _   _     _        __ _ _
 |  __ \                    | |            | (_) |   | | | |   (_)      / _(_) |
 | |  | | ___    _ __   ___ | |_    ___  __| |_| |_  | |_| |__  _ ___  | |_ _| | ___
 | |  | |/ _ \  | '_ \ / _ \| __|  / _ \/ _` | | __| | __| '_ \| / __| |  _| | |/ _ \
 | |__| | (_) | | | | | (_) | |_  |  __/ (_| | | |_  | |_| | | | \__ \ | | | | |  __/
 |_____/ \___/  |_| |_|\___/ \__|  \___|\__,_|_|\__|  \__|_| |_|_|___/ |_| |_|_|\___|

 * DO NOT EDIT THIS FILE!!
 *
 *  FOR CUSTOMIZE ccvvBaseService PLEASE EDIT ../ccvv.service.ts
 *
 *  -- THIS FILE WILL BE OVERWRITTEN ON THE NEXT SKAFFOLDER'S CODE GENERATION --
 *
 */
 // DEPENDENCIES
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

// CONFIG
import { environment } from '../../../environments/environment';

// MODEL
import { Ccvv } from '../../domain/cc1_db/ccvv';

/**
 * THIS SERVICE MAKE HTTP REQUEST TO SERVER, FOR CUSTOMIZE IT EDIT ../ccvv.service.ts
 */

/*
 * SCHEMA DB ccvv
 *
	{
		Cognome: {
			type: 'String',
			required : true
		},
		Nome: {
			type: 'String',
			required : true
		},
		Sesso: {
			type: 'String',
			required : true,
			enum : ["F", "M"]
		},
		//RELATIONS
		//EXTERNAL RELATIONS
	}
 *
 */
@Injectable()
export class CcvvBaseService {

    contextUrl: string = environment.endpoint + '/ccvv';
    constructor(
        protected http: HttpClient
        ) { }

    // CRUD METHODS

    /**
    * ccvvService.create
    *   @description CRUD ACTION create
    *
    */
    create(item: Ccvv): Observable<Ccvv> {
        return this.http
            .post<Ccvv>(this.contextUrl, item)
            .pipe(map(data => data));
    }

    /**
    * ccvvService.findByCognome
    *   @description CRUD ACTION findByCognome
    *   @param Objectid key Id of the resource Cognome to search
    *
    */
    findByCognome(id: string): Observable<Ccvv[]> {
        return this.http
            .get<Ccvv[]>(this.contextUrl + '/findByCognome/' + id)
            .pipe(
                map(response => response)
            );
    }

    /**
    * ccvvService.get
    *   @description CRUD ACTION get
    *   @param ObjectId id Id resource
    *
    */
    get(id: string): Observable<Ccvv> {
        return this.http
            .get<Ccvv>(this.contextUrl + '/' + id)
            .pipe(map(data => data));
    }

    /**
    * ccvvService.update
    *   @description CRUD ACTION update
    *   @param ObjectId id Id
    *
    */
    update(item: Ccvv): Observable<Ccvv> {
        return this.http
            .post<Ccvv>(this.contextUrl + '/' + item._id, item)
            .pipe(map(data => data));
    }


    // Custom APIs

}
